// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.5
// source: proto/broadcast.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserJoinedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCode   string                 `protobuf:"bytes,1,opt,name=session_code,json=sessionCode,proto3" json:"session_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserJoinedRequest) Reset() {
	*x = UserJoinedRequest{}
	mi := &file_proto_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserJoinedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinedRequest) ProtoMessage() {}

func (x *UserJoinedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinedRequest.ProtoReflect.Descriptor instead.
func (*UserJoinedRequest) Descriptor() ([]byte, []int) {
	return file_proto_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *UserJoinedRequest) GetSessionCode() string {
	if x != nil {
		return x.SessionCode
	}
	return ""
}

type UserLeavedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCode   string                 `protobuf:"bytes,1,opt,name=session_code,json=sessionCode,proto3" json:"session_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLeavedRequest) Reset() {
	*x = UserLeavedRequest{}
	mi := &file_proto_broadcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLeavedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeavedRequest) ProtoMessage() {}

func (x *UserLeavedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broadcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeavedRequest.ProtoReflect.Descriptor instead.
func (*UserLeavedRequest) Descriptor() ([]byte, []int) {
	return file_proto_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *UserLeavedRequest) GetSessionCode() string {
	if x != nil {
		return x.SessionCode
	}
	return ""
}

type UserAnsweredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionCode   string                 `protobuf:"bytes,2,opt,name=session_code,json=sessionCode,proto3" json:"session_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAnsweredRequest) Reset() {
	*x = UserAnsweredRequest{}
	mi := &file_proto_broadcast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnsweredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnsweredRequest) ProtoMessage() {}

func (x *UserAnsweredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broadcast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnsweredRequest.ProtoReflect.Descriptor instead.
func (*UserAnsweredRequest) Descriptor() ([]byte, []int) {
	return file_proto_broadcast_proto_rawDescGZIP(), []int{2}
}

func (x *UserAnsweredRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserAnsweredRequest) GetSessionCode() string {
	if x != nil {
		return x.SessionCode
	}
	return ""
}

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        uint32                 `protobuf:"varint,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	SessionCode   string                 `protobuf:"bytes,2,opt,name=session_code,json=sessionCode,proto3" json:"session_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_proto_broadcast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broadcast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_broadcast_proto_rawDescGZIP(), []int{3}
}

func (x *StartSessionRequest) GetQuizId() uint32 {
	if x != nil {
		return x.QuizId
	}
	return 0
}

func (x *StartSessionRequest) GetSessionCode() string {
	if x != nil {
		return x.SessionCode
	}
	return ""
}

type BroadcastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_proto_broadcast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broadcast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_proto_broadcast_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadcastResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_broadcast_proto protoreflect.FileDescriptor

const file_proto_broadcast_proto_rawDesc = "" +
	"\n" +
	"\x15proto/broadcast.proto\x12\x02ws\"6\n" +
	"\x11UserJoinedRequest\x12!\n" +
	"\fsession_code\x18\x01 \x01(\tR\vsessionCode\"6\n" +
	"\x11UserLeavedRequest\x12!\n" +
	"\fsession_code\x18\x01 \x01(\tR\vsessionCode\"Q\n" +
	"\x13UserAnsweredRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12!\n" +
	"\fsession_code\x18\x02 \x01(\tR\vsessionCode\"Q\n" +
	"\x13StartSessionRequest\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\rR\x06quizId\x12!\n" +
	"\fsession_code\x18\x02 \x01(\tR\vsessionCode\"G\n" +
	"\x11BroadcastResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa9\x02\n" +
	"\vBroadcaster\x12G\n" +
	"\x15BroadcastUserAnswered\x12\x17.ws.UserAnsweredRequest\x1a\x15.ws.BroadcastResponse\x12C\n" +
	"\x13BroadcastUserJoined\x12\x15.ws.UserJoinedRequest\x1a\x15.ws.BroadcastResponse\x12C\n" +
	"\x13BroadcastUserLeaved\x12\x15.ws.UserLeavedRequest\x1a\x15.ws.BroadcastResponse\x12G\n" +
	"\x15BroadcastStartSession\x12\x17.ws.StartSessionRequest\x1a\x15.ws.BroadcastResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_broadcast_proto_rawDescOnce sync.Once
	file_proto_broadcast_proto_rawDescData []byte
)

func file_proto_broadcast_proto_rawDescGZIP() []byte {
	file_proto_broadcast_proto_rawDescOnce.Do(func() {
		file_proto_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_broadcast_proto_rawDesc), len(file_proto_broadcast_proto_rawDesc)))
	})
	return file_proto_broadcast_proto_rawDescData
}

var file_proto_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_broadcast_proto_goTypes = []any{
	(*UserJoinedRequest)(nil),   // 0: ws.UserJoinedRequest
	(*UserLeavedRequest)(nil),   // 1: ws.UserLeavedRequest
	(*UserAnsweredRequest)(nil), // 2: ws.UserAnsweredRequest
	(*StartSessionRequest)(nil), // 3: ws.StartSessionRequest
	(*BroadcastResponse)(nil),   // 4: ws.BroadcastResponse
}
var file_proto_broadcast_proto_depIdxs = []int32{
	2, // 0: ws.Broadcaster.BroadcastUserAnswered:input_type -> ws.UserAnsweredRequest
	0, // 1: ws.Broadcaster.BroadcastUserJoined:input_type -> ws.UserJoinedRequest
	1, // 2: ws.Broadcaster.BroadcastUserLeaved:input_type -> ws.UserLeavedRequest
	3, // 3: ws.Broadcaster.BroadcastStartSession:input_type -> ws.StartSessionRequest
	4, // 4: ws.Broadcaster.BroadcastUserAnswered:output_type -> ws.BroadcastResponse
	4, // 5: ws.Broadcaster.BroadcastUserJoined:output_type -> ws.BroadcastResponse
	4, // 6: ws.Broadcaster.BroadcastUserLeaved:output_type -> ws.BroadcastResponse
	4, // 7: ws.Broadcaster.BroadcastStartSession:output_type -> ws.BroadcastResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_broadcast_proto_init() }
func file_proto_broadcast_proto_init() {
	if File_proto_broadcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_broadcast_proto_rawDesc), len(file_proto_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_broadcast_proto_goTypes,
		DependencyIndexes: file_proto_broadcast_proto_depIdxs,
		MessageInfos:      file_proto_broadcast_proto_msgTypes,
	}.Build()
	File_proto_broadcast_proto = out.File
	file_proto_broadcast_proto_goTypes = nil
	file_proto_broadcast_proto_depIdxs = nil
}
